"""Representative seed dataset.

These are realistic, representative GAF-style roofing-contractor records for the
NYC metro area (ZIP 10013, 25-mile radius). They mirror the exact shape the live
``GafScraper`` produces, so the pipeline, storage layer, scoring, and UI can be
demonstrated end-to-end **without** network access.

When the app is run on a machine with open network + valid keys, the live
scraper replaces this list with the real GAF directory results.
"""
from __future__ import annotations

# Fields mirror GafScraper.scrape() output (see gaf.py -> _to_record).
SEED_CONTRACTORS: list[dict] = [
    {
        "name": "Skyline Roofing & Waterproofing",
        "certification": "Master Elite",
        "phone": "(212) 555-0142",
        "website": "https://skylineroofingnyc.example.com",
        "address": "212 Canal St",
        "city": "New York",
        "state": "NY",
        "zip_code": "10013",
        "distance_miles": 0.4,
        "rating": 4.8,
        "review_count": 312,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/skyline-roofing-waterproofing",
    },
    {
        "name": "Empire State Roofing Co.",
        "certification": "Master Elite",
        "phone": "(212) 555-0188",
        "website": "https://empirestateroofing.example.com",
        "address": "88 Lafayette St",
        "city": "New York",
        "state": "NY",
        "zip_code": "10013",
        "distance_miles": 0.9,
        "rating": 4.6,
        "review_count": 204,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/empire-state-roofing",
    },
    {
        "name": "Hudson River Exteriors",
        "certification": "Certified",
        "phone": "(212) 555-0233",
        "website": "https://hudsonriverexteriors.example.com",
        "address": "455 Greenwich St",
        "city": "New York",
        "state": "NY",
        "zip_code": "10013",
        "distance_miles": 1.2,
        "rating": 4.4,
        "review_count": 96,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/hudson-river-exteriors",
    },
    {
        "name": "Brooklyn Heights Roofing",
        "certification": "Master Elite",
        "phone": "(718) 555-0119",
        "website": "https://bkheightsroofing.example.com",
        "address": "140 Montague St",
        "city": "Brooklyn",
        "state": "NY",
        "zip_code": "11201",
        "distance_miles": 2.6,
        "rating": 4.9,
        "review_count": 418,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/brooklyn-heights-roofing",
    },
    {
        "name": "Five Boroughs Roofing Group",
        "certification": "Certified",
        "phone": "(718) 555-0177",
        "website": "https://fiveboroughsroofing.example.com",
        "address": "31-15 Queens Blvd",
        "city": "Long Island City",
        "state": "NY",
        "zip_code": "11101",
        "distance_miles": 3.8,
        "rating": 4.2,
        "review_count": 73,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/five-boroughs-roofing",
    },
    {
        "name": "Liberty Roofing & Solar",
        "certification": "Master Elite",
        "phone": "(201) 555-0150",
        "website": "https://libertyroofingsolar.example.com",
        "address": "300 Hudson St",
        "city": "Jersey City",
        "state": "NJ",
        "zip_code": "07302",
        "distance_miles": 4.1,
        "rating": 4.7,
        "review_count": 268,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/liberty-roofing-solar",
    },
    {
        "name": "Tri-State Commercial Roofing",
        "certification": "Master Elite",
        "phone": "(212) 555-0291",
        "website": "https://tristatecommercialroofing.example.com",
        "address": "620 8th Ave",
        "city": "New York",
        "state": "NY",
        "zip_code": "10018",
        "distance_miles": 2.2,
        "rating": 4.5,
        "review_count": 151,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/tri-state-commercial-roofing",
    },
    {
        "name": "Gotham Roofing Solutions",
        "certification": "Certified",
        "phone": "(212) 555-0260",
        "website": "https://gothamroofing.example.com",
        "address": "19 W 34th St",
        "city": "New York",
        "state": "NY",
        "zip_code": "10001",
        "distance_miles": 2.0,
        "rating": 4.1,
        "review_count": 58,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/gotham-roofing-solutions",
    },
    {
        "name": "Atlas Residential Roofing",
        "certification": "Certified",
        "phone": "(718) 555-0204",
        "website": "https://atlasresidentialroofing.example.com",
        "address": "2110 Williamsbridge Rd",
        "city": "Bronx",
        "state": "NY",
        "zip_code": "10461",
        "distance_miles": 9.3,
        "rating": 4.3,
        "review_count": 112,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/atlas-residential-roofing",
    },
    {
        "name": "Harborview Roofing Contractors",
        "certification": "Master Elite",
        "phone": "(718) 555-0233",
        "website": "https://harborviewroofing.example.com",
        "address": "1230 Bay St",
        "city": "Staten Island",
        "state": "NY",
        "zip_code": "10305",
        "distance_miles": 8.7,
        "rating": 4.6,
        "review_count": 189,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/harborview-roofing",
    },
    {
        "name": "Metro Flat Roof Specialists",
        "certification": "Certified",
        "phone": "(212) 555-0318",
        "website": "https://metroflatroof.example.com",
        "address": "525 W 52nd St",
        "city": "New York",
        "state": "NY",
        "zip_code": "10019",
        "distance_miles": 3.0,
        "rating": 4.0,
        "review_count": 44,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/metro-flat-roof",
    },
    {
        "name": "Riverside Roofing & Siding",
        "certification": "Certified",
        "phone": "(201) 555-0222",
        "website": "https://riversideroofingsiding.example.com",
        "address": "70 Hudson St",
        "city": "Hoboken",
        "state": "NJ",
        "zip_code": "07030",
        "distance_miles": 3.5,
        "rating": 4.4,
        "review_count": 87,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/riverside-roofing-siding",
    },
    {
        "name": "Knickerbocker Roofing",
        "certification": "Master Elite",
        "phone": "(718) 555-0290",
        "website": "https://knickerbockerroofing.example.com",
        "address": "456 Myrtle Ave",
        "city": "Brooklyn",
        "state": "NY",
        "zip_code": "11205",
        "distance_miles": 3.2,
        "rating": 4.7,
        "review_count": 221,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/knickerbocker-roofing",
    },
    {
        "name": "Parkside Home Exteriors",
        "certification": None,
        "phone": "(914) 555-0145",
        "website": "https://parksidehomeexteriors.example.com",
        "address": "12 Mamaroneck Ave",
        "city": "White Plains",
        "state": "NY",
        "zip_code": "10601",
        "distance_miles": 22.4,
        "rating": 3.9,
        "review_count": 31,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/parkside-home-exteriors",
    },
    {
        "name": "Cathedral Roofing & Restoration",
        "certification": "Master Elite",
        "phone": "(212) 555-0399",
        "website": "https://cathedralroofing.example.com",
        "address": "1047 Amsterdam Ave",
        "city": "New York",
        "state": "NY",
        "zip_code": "10025",
        "distance_miles": 5.4,
        "rating": 4.8,
        "review_count": 276,
        "source_url": "https://www.gaf.com/en-us/roofing-contractors/cathedral-roofing-restoration",
    },
]
